/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtectionDescriptorModule"
 * 	found in "protection_descriptor.asn1"
 */

#ifndef	_DescriptorType_H_
#define	_DescriptorType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DescriptorType */
typedef OBJECT_IDENTIFIER_t	 DescriptorType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DescriptorType;
asn_struct_free_f DescriptorType_free;
asn_struct_print_f DescriptorType_print;
asn_constr_check_f DescriptorType_constraint;
ber_type_decoder_f DescriptorType_decode_ber;
der_type_encoder_f DescriptorType_encode_der;
xer_type_decoder_f DescriptorType_decode_xer;
xer_type_encoder_f DescriptorType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DescriptorType_H_ */
#include <asn_internal.h>
