/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "my_key_info.asn1"
 */

#ifndef	_MyKeyInfo_H_
#define	_MyKeyInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyKeyInfo */
typedef struct MyKeyInfo {
	OCTET_STRING_t	 iv;
	long	 modulus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MyKeyInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyKeyInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _MyKeyInfo_H_ */
#include <asn_internal.h>
