/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtectionDescriptorModule"
 * 	found in "protection_descriptor.asn1"
 */

#ifndef	_ProtectionDescriptor_H_
#define	_ProtectionDescriptor_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptorType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProviderAttributes;

/* ProtectionDescriptor */
typedef struct ProtectionDescriptor {
	DescriptorType_t	 descriptorType;
	struct attrs {
		A_SEQUENCE_OF(struct ProviderAttributes) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} attrs;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtectionDescriptor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectionDescriptor;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProviderAttributes.h"

#endif	/* _ProtectionDescriptor_H_ */
#include <asn_internal.h>
