/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtectionDescriptorModule"
 * 	found in "protection_descriptor.asn1"
 */

#include "ProtectionDescriptor.h"

static asn_TYPE_member_t asn_MBR_attrs_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ProviderAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_attrs_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_attrs_specs_3 = {
	sizeof(struct attrs),
	offsetof(struct attrs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_attrs_3 = {
	"attrs",
	"attrs",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_attrs_tags_3,
	sizeof(asn_DEF_attrs_tags_3)
		/sizeof(asn_DEF_attrs_tags_3[0]), /* 1 */
	asn_DEF_attrs_tags_3,	/* Same as above */
	sizeof(asn_DEF_attrs_tags_3)
		/sizeof(asn_DEF_attrs_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_attrs_3,
	1,	/* Single element */
	&asn_SPC_attrs_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ProtectionDescriptor_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProtectionDescriptor, descriptorType),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_DescriptorType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"descriptorType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProtectionDescriptor, attrs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_attrs_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attrs"
		},
};
static const ber_tlv_tag_t asn_DEF_ProtectionDescriptor_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProtectionDescriptor_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* descriptorType */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* attrs */
};
static asn_SEQUENCE_specifics_t asn_SPC_ProtectionDescriptor_specs_1 = {
	sizeof(struct ProtectionDescriptor),
	offsetof(struct ProtectionDescriptor, _asn_ctx),
	asn_MAP_ProtectionDescriptor_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ProtectionDescriptor = {
	"ProtectionDescriptor",
	"ProtectionDescriptor",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ProtectionDescriptor_tags_1,
	sizeof(asn_DEF_ProtectionDescriptor_tags_1)
		/sizeof(asn_DEF_ProtectionDescriptor_tags_1[0]), /* 1 */
	asn_DEF_ProtectionDescriptor_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtectionDescriptor_tags_1)
		/sizeof(asn_DEF_ProtectionDescriptor_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ProtectionDescriptor_1,
	2,	/* Elements count */
	&asn_SPC_ProtectionDescriptor_specs_1	/* Additional specs */
};

