/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtectionDescriptorModule"
 * 	found in "protection_descriptor.asn1"
 */

#ifndef	_ProviderAttribute_H_
#define	_ProviderAttribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProviderAttribute */
typedef struct ProviderAttribute {
	UTF8String_t	 providerName;
	UTF8String_t	 providerValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProviderAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProviderAttribute;

#ifdef __cplusplus
}
#endif

#endif	/* _ProviderAttribute_H_ */
#include <asn_internal.h>
