/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ProtectionDescriptorModule"
 * 	found in "protection_descriptor.asn1"
 */

#ifndef	_ProviderAttributes_H_
#define	_ProviderAttributes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProviderAttribute;

/* ProviderAttributes */
typedef struct ProviderAttributes {
	A_SEQUENCE_OF(struct ProviderAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProviderAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProviderAttributes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProviderAttribute.h"

#endif	/* _ProviderAttributes_H_ */
#include <asn_internal.h>
